//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.ChronologicalEventList;

namespace zenonExtensions
{
  public static class ChronologicalEventListExtension
  {
/// Sets FilterPartGUID
    public static void SetFilterPartGUID(this IChronologicalEventList cel, System.Guid value)
    {
      cel.SetDynamicProperty("FilterPartGUID", value);
    }

/// Gets FilterPartGUID
    public static System.Guid GetFilterPartGUID(this IChronologicalEventList cel)
    {
      return (System.Guid) cel.GetDynamicProperty("FilterPartGUID");
    }

/// Sets EditableInRT
    public static void SetEditableInRT(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("EditableInRT", value);
    }

/// Gets EditableInRT
    public static bool GetEditableInRT(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("EditableInRT");
    }

/// Sets FileName
    public static void SetFileName(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("FileName", value);
    }

/// Gets FileName
    public static string GetFileName(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("FileName");
    }

/// Sets VarFilter
    public static void SetVarFilter(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("VarFilter", value);
    }

/// Gets VarFilter
    public static string GetVarFilter(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("VarFilter");
    }

/// Sets FilterTitel
    public static void SetFilterTitel(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("FilterTitel", value);
    }

/// Gets FilterTitel
    public static string GetFilterTitel(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("FilterTitel");
    }

/// Sets IsFilterRT
    public static void SetIsFilterRT(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsFilterRT", value);
    }

/// Gets IsFilterRT
    public static bool GetIsFilterRT(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsFilterRT");
    }

/// Sets IsMatchCase
    public static void SetIsMatchCase(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsMatchCase", value);
    }

/// Gets IsMatchCase
    public static bool GetIsMatchCase(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsMatchCase");
    }

/// Sets IsFromFiles
    public static void SetIsFromFiles(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsFromFiles", value);
    }

/// Gets IsFromFiles
    public static bool GetIsFromFiles(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsFromFiles");
    }

/// Sets IsReadAll
    public static void SetIsReadAll(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsReadAll", value);
    }

/// Gets IsReadAll
    public static bool GetIsReadAll(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsReadAll");
    }

/// Sets IsAutoName
    public static void SetIsAutoName(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsAutoName", value);
    }

/// Gets IsAutoName
    public static bool GetIsAutoName(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsAutoName");
    }

/// Sets IsAML
    public static void SetIsAML(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsAML", value);
    }

/// Gets IsAML
    public static bool GetIsAML(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsAML");
    }

/// Sets IsDBASE
    public static void SetIsDBASE(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsDBASE", value);
    }

/// Gets IsDBASE
    public static bool GetIsDBASE(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsDBASE");
    }

/// Sets IsXML
    public static void SetIsXML(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsXML", value);
    }

/// Gets IsXML
    public static bool GetIsXML(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsXML");
    }

/// Sets IsRelationTime
    public static void SetIsRelationTime(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsRelationTime", value);
    }

/// Gets IsRelationTime
    public static bool GetIsRelationTime(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsRelationTime");
    }

/// Sets IsUnicode
    public static void SetIsUnicode(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsUnicode", value);
    }

/// Gets IsUnicode
    public static bool GetIsUnicode(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsUnicode");
    }

/// Sets IsIncremental
    public static void SetIsIncremental(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsIncremental", value);
    }

/// Gets IsIncremental
    public static bool GetIsIncremental(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsIncremental");
    }

/// Sets IsFilterExp
    public static void SetIsFilterExp(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsFilterExp", value);
    }

/// Gets IsFilterExp
    public static bool GetIsFilterExp(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsFilterExp");
    }

/// Sets IsAcknowledged
    public static void SetIsAcknowledged(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsAcknowledged", value);
    }

/// Gets IsAcknowledged
    public static bool GetIsAcknowledged(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsAcknowledged");
    }

/// Sets IsAscentOnly
    public static void SetIsAscentOnly(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsAscentOnly", value);
    }

/// Gets IsAscentOnly
    public static bool GetIsAscentOnly(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsAscentOnly");
    }

/// Sets EntriesCount
    public static void SetEntriesCount(this IChronologicalEventList cel, ushort value)
    {
      cel.SetDynamicProperty("EntriesCount", value);
    }

/// Gets EntriesCount
    public static ushort GetEntriesCount(this IChronologicalEventList cel)
    {
      return (ushort) cel.GetDynamicProperty("EntriesCount");
    }

/// Sets Font
    public static void SetFont(this IChronologicalEventList cel, ushort value)
    {
      cel.SetDynamicProperty("Font", value);
    }

/// Gets Font
    public static ushort GetFont(this IChronologicalEventList cel)
    {
      return (ushort) cel.GetDynamicProperty("Font");
    }

/// Sets Classes
    public static void SetClasses(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Classes", value);
    }

/// Gets Classes
    public static string GetClasses(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Classes");
    }

/// Sets Groups
    public static void SetGroups(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Groups", value);
    }

/// Gets Groups
    public static string GetGroups(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Groups");
    }

/// Sets ResString
    public static void SetResString(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ResString", value);
    }

/// Gets ResString
    public static string GetResString(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ResString");
    }

/// Sets IncTime
    public static void SetIncTime(this IChronologicalEventList cel, uint value)
    {
      cel.SetDynamicProperty("IncTime", value);
    }

/// Gets IncTime
    public static uint GetIncTime(this IChronologicalEventList cel)
    {
      return (uint) cel.GetDynamicProperty("IncTime");
    }

/// Sets mSeconds
    public static void SetmSeconds(this IChronologicalEventList cel, ushort value)
    {
      cel.SetDynamicProperty("mSeconds", value);
    }

/// Gets mSeconds
    public static ushort GetmSeconds(this IChronologicalEventList cel)
    {
      return (ushort) cel.GetDynamicProperty("mSeconds");
    }

/// Sets ProjectNames
    public static void SetProjectNames(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ProjectNames", value);
    }

/// Gets ProjectNames
    public static string GetProjectNames(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ProjectNames");
    }

/// Sets IsSQL
    public static void SetIsSQL(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsSQL", value);
    }

/// Gets IsSQL
    public static bool GetIsSQL(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsSQL");
    }

/// Sets SQLBase
    public static void SetSQLBase(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("SQLBase", value);
    }

/// Gets SQLBase
    public static string GetSQLBase(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("SQLBase");
    }

/// Sets SQLTable
    public static void SetSQLTable(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("SQLTable", value);
    }

/// Gets SQLTable
    public static string GetSQLTable(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("SQLTable");
    }

/// Sets Areas
    public static void SetAreas(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Areas", value);
    }

/// Gets Areas
    public static string GetAreas(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Areas");
    }

/// Sets IsGoneOnly
    public static void SetIsGoneOnly(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsGoneOnly", value);
    }

/// Gets IsGoneOnly
    public static bool GetIsGoneOnly(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsGoneOnly");
    }

/// Sets NeedComment
    public static void SetNeedComment(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("NeedComment", value);
    }

/// Gets NeedComment
    public static bool GetNeedComment(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("NeedComment");
    }

/// Sets NeedAlarmCause
    public static void SetNeedAlarmCause(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("NeedAlarmCause", value);
    }

/// Gets NeedAlarmCause
    public static bool GetNeedAlarmCause(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("NeedAlarmCause");
    }

/// Sets CategoryFilter
    public static void SetCategoryFilter(this IChronologicalEventList cel, object value)
    {
      cel.SetDynamicProperty("CategoryFilter", value);
    }

/// Gets CategoryFilter
    public static object GetCategoryFilter(this IChronologicalEventList cel)
    {
      return (object) cel.GetDynamicProperty("CategoryFilter");
    }

/// Sets HideInactiveAlarmGroups
    public static void SetHideInactiveAlarmGroups(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("HideInactiveAlarmGroups", value);
    }

/// Gets HideInactiveAlarmGroups
    public static bool GetHideInactiveAlarmGroups(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("HideInactiveAlarmGroups");
    }

/// Sets HideInactiveAlarmClasses
    public static void SetHideInactiveAlarmClasses(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("HideInactiveAlarmClasses", value);
    }

/// Gets HideInactiveAlarmClasses
    public static bool GetHideInactiveAlarmClasses(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("HideInactiveAlarmClasses");
    }

/// Sets AcknowledgedOnly
    public static void SetAcknowledgedOnly(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("AcknowledgedOnly", value);
    }

/// Gets AcknowledgedOnly
    public static bool GetAcknowledgedOnly(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("AcknowledgedOnly");
    }

/// Sets NonAcknowledgedOrUnclearedOnly
    public static void SetNonAcknowledgedOrUnclearedOnly(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("NonAcknowledgedOrUnclearedOnly", value);
    }

/// Gets NonAcknowledgedOrUnclearedOnly
    public static bool GetNonAcknowledgedOrUnclearedOnly(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("NonAcknowledgedOrUnclearedOnly");
    }

/// Sets UseExportLanguage
    public static void SetUseExportLanguage(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("UseExportLanguage", value);
    }

/// Gets UseExportLanguage
    public static bool GetUseExportLanguage(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("UseExportLanguage");
    }

/// Sets ExportLanguage
    public static void SetExportLanguage(this IChronologicalEventList cel, ushort value)
    {
      cel.SetDynamicProperty("ExportLanguage", value);
    }

/// Gets ExportLanguage
    public static ushort GetExportLanguage(this IChronologicalEventList cel)
    {
      return (ushort) cel.GetDynamicProperty("ExportLanguage");
    }

/// Sets StandardDisplayMode
    public static void SetStandardDisplayMode(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("StandardDisplayMode", value);
    }

/// Gets StandardDisplayMode
    public static bool GetStandardDisplayMode(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("StandardDisplayMode");
    }

/// Sets ShowSysEntriesForever
    public static void SetShowSysEntriesForever(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("ShowSysEntriesForever", value);
    }

/// Gets ShowSysEntriesForever
    public static bool GetShowSysEntriesForever(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("ShowSysEntriesForever");
    }

/// Sets ARVTime1
    public static void SetARVTime1(this IChronologicalEventList cel, uint value)
    {
      cel.SetDynamicProperty("ARVTime1", value);
    }

/// Gets ARVTime1
    public static uint GetARVTime1(this IChronologicalEventList cel)
    {
      return (uint) cel.GetDynamicProperty("ARVTime1");
    }

/// Sets ARVTime2
    public static void SetARVTime2(this IChronologicalEventList cel, uint value)
    {
      cel.SetDynamicProperty("ARVTime2", value);
    }

/// Gets ARVTime2
    public static uint GetARVTime2(this IChronologicalEventList cel)
    {
      return (uint) cel.GetDynamicProperty("ARVTime2");
    }

/// Sets Options
    public static void SetOptions(this IChronologicalEventList cel, ushort value)
    {
      cel.SetDynamicProperty("Options", value);
    }

/// Gets Options
    public static ushort GetOptions(this IChronologicalEventList cel)
    {
      return (ushort) cel.GetDynamicProperty("Options");
    }

/// Sets TimeFormat
    public static void SetTimeFormat(this IChronologicalEventList cel, ushort value)
    {
      cel.SetDynamicProperty("TimeFormat", value);
    }

/// Gets TimeFormat
    public static ushort GetTimeFormat(this IChronologicalEventList cel)
    {
      return (ushort) cel.GetDynamicProperty("TimeFormat");
    }

/// Sets AddLen
    public static void SetAddLen(this IChronologicalEventList cel, ushort value)
    {
      cel.SetDynamicProperty("AddLen", value);
    }

/// Gets AddLen
    public static ushort GetAddLen(this IChronologicalEventList cel)
    {
      return (ushort) cel.GetDynamicProperty("AddLen");
    }

/// Sets Length
    public static void SetLength(this IChronologicalEventList cel, uint value)
    {
      cel.SetDynamicProperty("Length", value);
    }

/// Gets Length
    public static uint GetLength(this IChronologicalEventList cel)
    {
      return (uint) cel.GetDynamicProperty("Length");
    }

/// Sets Offset
    public static void SetOffset(this IChronologicalEventList cel, uint value)
    {
      cel.SetDynamicProperty("Offset", value);
    }

/// Gets Offset
    public static uint GetOffset(this IChronologicalEventList cel)
    {
      return (uint) cel.GetDynamicProperty("Offset");
    }

/// Sets ModifyTimePeriod
    public static void SetModifyTimePeriod(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("ModifyTimePeriod", value);
    }

/// Gets ModifyTimePeriod
    public static bool GetModifyTimePeriod(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("ModifyTimePeriod");
    }

/// Sets BoxenType
    public static void SetBoxenType(this IChronologicalEventList cel, ushort value)
    {
      cel.SetDynamicProperty("BoxenType", value);
    }

/// Gets BoxenType
    public static ushort GetBoxenType(this IChronologicalEventList cel)
    {
      return (ushort) cel.GetDynamicProperty("BoxenType");
    }

/// Sets NoDialogForTimePeriod
    public static void SetNoDialogForTimePeriod(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("NoDialogForTimePeriod", value);
    }

/// Gets NoDialogForTimePeriod
    public static bool GetNoDialogForTimePeriod(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("NoDialogForTimePeriod");
    }

/// Sets Count
    public static void SetCount(this IChronologicalEventList cel, uint value)
    {
      cel.SetDynamicProperty("Count", value);
    }

/// Gets Count
    public static uint GetCount(this IChronologicalEventList cel)
    {
      return (uint) cel.GetDynamicProperty("Count");
    }

/// Sets TimeLimits
    public static void SetTimeLimits(this IChronologicalEventList cel, ushort value)
    {
      cel.SetDynamicProperty("TimeLimits", value);
    }

/// Gets TimeLimits
    public static ushort GetTimeLimits(this IChronologicalEventList cel)
    {
      return (ushort) cel.GetDynamicProperty("TimeLimits");
    }

/// Sets ArvLotList
    public static void SetArvLotList(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ArvLotList", value);
    }

/// Gets ArvLotList
    public static string GetArvLotList(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ArvLotList");
    }

/// Sets ChargeRelative
    public static void SetChargeRelative(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("ChargeRelative", value);
    }

/// Gets ChargeRelative
    public static bool GetChargeRelative(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("ChargeRelative");
    }

/// Sets ChargenNameFilterType
    public static void SetChargenNameFilterType(this IChronologicalEventList cel, ushort value)
    {
      cel.SetDynamicProperty("ChargenNameFilterType", value);
    }

/// Gets ChargenNameFilterType
    public static ushort GetChargenNameFilterType(this IChronologicalEventList cel)
    {
      return (ushort) cel.GetDynamicProperty("ChargenNameFilterType");
    }

/// Sets Lot name from variable
    public static void SetChargenNameFilterVar(this IChronologicalEventList cel, object value)
    {
      cel.SetDynamicProperty("ChargenNameFilterVar", value);
    }

/// Gets Lot name from variable
    public static object GetChargenNameFilterVar(this IChronologicalEventList cel)
    {
      return (object) cel.GetDynamicProperty("ChargenNameFilterVar");
    }

/// Sets ArchiveNameFilterType
    public static void SetArchiveNameFilterType(this IChronologicalEventList cel, ushort value)
    {
      cel.SetDynamicProperty("ArchiveNameFilterType", value);
    }

/// Gets ArchiveNameFilterType
    public static ushort GetArchiveNameFilterType(this IChronologicalEventList cel)
    {
      return (ushort) cel.GetDynamicProperty("ArchiveNameFilterType");
    }

/// Sets Archive name from variable
    public static void SetArchiveNameFilterVar(this IChronologicalEventList cel, object value)
    {
      cel.SetDynamicProperty("ArchiveNameFilterVar", value);
    }

/// Gets Archive name from variable
    public static object GetArchiveNameFilterVar(this IChronologicalEventList cel)
    {
      return (object) cel.GetDynamicProperty("ArchiveNameFilterVar");
    }

/// Sets ArchiveName
    public static void SetArchiveName(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ArchiveName", value);
    }

/// Gets ArchiveName
    public static string GetArchiveName(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ArchiveName");
    }

/// Sets LotName
    public static void SetLotName(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("LotName", value);
    }

/// Gets LotName
    public static string GetLotName(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("LotName");
    }

/// Sets TimeFilterType
    public static void SetTimeFilterType(this IChronologicalEventList cel, byte value)
    {
      cel.SetDynamicProperty("TimeFilterType", value);
    }

/// Gets TimeFilterType
    public static byte GetTimeFilterType(this IChronologicalEventList cel)
    {
      return (byte) cel.GetDynamicProperty("TimeFilterType");
    }

/// Sets DoneLots
    public static void SetDoneLots(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("DoneLots", value);
    }

/// Gets DoneLots
    public static bool GetDoneLots(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("DoneLots");
    }

/// Sets OpenLots
    public static void SetOpenLots(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("OpenLots", value);
    }

/// Gets OpenLots
    public static bool GetOpenLots(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("OpenLots");
    }

/// Sets State
    public static void SetState(this IChronologicalEventList cel, byte value)
    {
      cel.SetDynamicProperty("State", value);
    }

/// Gets State
    public static byte GetState(this IChronologicalEventList cel)
    {
      return (byte) cel.GetDynamicProperty("State");
    }

/// Sets BatchIdentifierUsage
    public static void SetBatchIdentifierUsage(this IChronologicalEventList cel, byte value)
    {
      cel.SetDynamicProperty("BatchIdentifierUsage", value);
    }

/// Gets BatchIdentifierUsage
    public static byte GetBatchIdentifierUsage(this IChronologicalEventList cel)
    {
      return (byte) cel.GetDynamicProperty("BatchIdentifierUsage");
    }

/// Sets Screen for time filter
    public static void SetRelatedPicture(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("RelatedPicture", value);
    }

/// Gets Screen for time filter
    public static string GetRelatedPicture(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("RelatedPicture");
    }

/// Sets Equipment Groups
    public static void SetSystemModelGroup(this IChronologicalEventList cel, object value)
    {
      cel.SetDynamicProperty("SystemModelGroup", value);
    }

/// Gets Equipment Groups
    public static object GetSystemModelGroup(this IChronologicalEventList cel)
    {
      return (object) cel.GetDynamicProperty("SystemModelGroup");
    }

/// Sets VarCount
    public static void SetVarCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("VarCount", value);
    }

/// Gets VarCount
    public static short GetVarCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("VarCount");
    }

/// Sets TagCount
    public static void SetTagCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("TagCount", value);
    }

/// Gets TagCount
    public static short GetTagCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("TagCount");
    }

/// Sets AlarmCount
    public static void SetAlarmCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("AlarmCount", value);
    }

/// Gets AlarmCount
    public static short GetAlarmCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("AlarmCount");
    }

/// Sets StatCount
    public static void SetStatCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("StatCount", value);
    }

/// Gets StatCount
    public static short GetStatCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("StatCount");
    }

/// Sets ValCount
    public static void SetValCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ValCount", value);
    }

/// Gets ValCount
    public static short GetValCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ValCount");
    }

/// Sets UserCount
    public static void SetUserCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("UserCount", value);
    }

/// Gets UserCount
    public static short GetUserCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("UserCount");
    }

/// Sets UserNameCount
    public static void SetUserNameCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("UserNameCount", value);
    }

/// Gets UserNameCount
    public static short GetUserNameCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("UserNameCount");
    }

/// Sets CompCount
    public static void SetCompCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("CompCount", value);
    }

/// Gets CompCount
    public static short GetCompCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("CompCount");
    }

/// Sets RTextCount
    public static void SetRTextCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("RTextCount", value);
    }

/// Gets RTextCount
    public static short GetRTextCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("RTextCount");
    }

/// Sets ProjectCount
    public static void SetProjectCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ProjectCount", value);
    }

/// Gets ProjectCount
    public static short GetProjectCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ProjectCount");
    }

/// Sets ClassCount
    public static void SetClassCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ClassCount", value);
    }

/// Gets ClassCount
    public static short GetClassCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ClassCount");
    }

/// Sets ClassNrCount
    public static void SetClassNrCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ClassNrCount", value);
    }

/// Gets ClassNrCount
    public static short GetClassNrCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ClassNrCount");
    }

/// Sets GroupCount
    public static void SetGroupCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("GroupCount", value);
    }

/// Gets GroupCount
    public static short GetGroupCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("GroupCount");
    }

/// Sets GroupNrCount
    public static void SetGroupNrCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("GroupNrCount", value);
    }

/// Gets GroupNrCount
    public static short GetGroupNrCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("GroupNrCount");
    }

/// Sets Entry
    public static void SetEntry(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Entry", value);
    }

/// Gets Entry
    public static string GetEntry(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Entry");
    }

/// Sets EntryAll
    public static void SetEntryAll(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("EntryAll", value);
    }

/// Gets EntryAll
    public static string GetEntryAll(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("EntryAll");
    }

/// Sets Name
    public static void SetName(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Name", value);
    }

/// Gets Name
    public static string GetName(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Name");
    }

/// Sets TagNr
    public static void SetTagNr(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("TagNr", value);
    }

/// Gets TagNr
    public static string GetTagNr(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("TagNr");
    }

/// Sets Text
    public static void SetText(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Text", value);
    }

/// Gets Text
    public static string GetText(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Text");
    }

/// Sets Comes
    public static void SetComes(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Comes", value);
    }

/// Gets Comes
    public static string GetComes(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Comes");
    }

/// Sets Goes
    public static void SetGoes(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Goes", value);
    }

/// Gets Goes
    public static string GetGoes(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Goes");
    }

/// Sets Acknowledged
    public static void SetAcknowledged(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Acknowledged", value);
    }

/// Gets Acknowledged
    public static string GetAcknowledged(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Acknowledged");
    }

/// Sets Stop
    public static void SetStop(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Stop", value);
    }

/// Gets Stop
    public static string GetStop(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Stop");
    }

/// Sets Status
    public static void SetStatus(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Status", value);
    }

/// Gets Status
    public static string GetStatus(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Status");
    }

/// Sets Value
    public static void SetValue(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Value", value);
    }

/// Gets Value
    public static string GetValue(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Value");
    }

/// Sets User
    public static void SetUser(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("User", value);
    }

/// Gets User
    public static string GetUser(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("User");
    }

/// Sets UserName
    public static void SetUserName(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("UserName", value);
    }

/// Gets UserName
    public static string GetUserName(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("UserName");
    }

/// Sets Computer
    public static void SetComputer(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Computer", value);
    }

/// Gets Computer
    public static string GetComputer(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Computer");
    }

/// Sets ReaktTime
    public static void SetReaktTime(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ReaktTime", value);
    }

/// Gets ReaktTime
    public static string GetReaktTime(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ReaktTime");
    }

/// Sets ReaktCount
    public static void SetReaktCount(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ReaktCount", value);
    }

/// Gets ReaktCount
    public static string GetReaktCount(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ReaktCount");
    }

/// Sets ReaktStat
    public static void SetReaktStat(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ReaktStat", value);
    }

/// Gets ReaktStat
    public static string GetReaktStat(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ReaktStat");
    }

/// Sets AktText
    public static void SetAktText(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("AktText", value);
    }

/// Gets AktText
    public static string GetAktText(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("AktText");
    }

/// Sets Project
    public static void SetProject(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Project", value);
    }

/// Gets Project
    public static string GetProject(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Project");
    }

/// Sets Class
    public static void SetClass(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Class", value);
    }

/// Gets Class
    public static string GetClass(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Class");
    }

/// Sets ClassNr
    public static void SetClassNr(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ClassNr", value);
    }

/// Gets ClassNr
    public static string GetClassNr(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ClassNr");
    }

/// Sets Group
    public static void SetGroup(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Group", value);
    }

/// Gets Group
    public static string GetGroup(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Group");
    }

/// Sets GroupNr
    public static void SetGroupNr(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("GroupNr", value);
    }

/// Gets GroupNr
    public static string GetGroupNr(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("GroupNr");
    }

/// Sets IsDate
    public static void SetIsDate(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsDate", value);
    }

/// Gets IsDate
    public static bool GetIsDate(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsDate");
    }

/// Sets IsTime
    public static void SetIsTime(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsTime", value);
    }

/// Gets IsTime
    public static bool GetIsTime(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsTime");
    }

/// Sets IsMilliseconds
    public static void SetIsMilliseconds(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsMilliseconds", value);
    }

/// Gets IsMilliseconds
    public static bool GetIsMilliseconds(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsMilliseconds");
    }

/// Sets IsDynLimitFile
    public static void SetIsDynLimitFile(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsDynLimitFile", value);
    }

/// Gets IsDynLimitFile
    public static bool GetIsDynLimitFile(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsDynLimitFile");
    }

/// Sets IsMicroSeconds
    public static void SetIsMicroSeconds(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsMicroSeconds", value);
    }

/// Gets IsMicroSeconds
    public static bool GetIsMicroSeconds(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsMicroSeconds");
    }

/// Sets ShowGrid
    public static void SetShowGrid(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("ShowGrid", value);
    }

/// Gets ShowGrid
    public static bool GetShowGrid(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("ShowGrid");
    }

/// Sets UseOptionalColors
    public static void SetUseOptionalColors(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("UseOptionalColors", value);
    }

/// Gets UseOptionalColors
    public static bool GetUseOptionalColors(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("UseOptionalColors");
    }

/// Sets StatusCaption
    public static void SetStatusCaption(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("StatusCaption", value);
    }

/// Gets StatusCaption
    public static string GetStatusCaption(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("StatusCaption");
    }

/// Sets Color1
    public static void SetColor1(this IChronologicalEventList cel, uint value)
    {
      cel.SetDynamicProperty("Color1", value);
    }

/// Gets Color1
    public static uint GetColor1(this IChronologicalEventList cel)
    {
      return (uint) cel.GetDynamicProperty("Color1");
    }

/// Sets Color2
    public static void SetColor2(this IChronologicalEventList cel, uint value)
    {
      cel.SetDynamicProperty("Color2", value);
    }

/// Gets Color2
    public static uint GetColor2(this IChronologicalEventList cel)
    {
      return (uint) cel.GetDynamicProperty("Color2");
    }

/// Sets StatusCaptionNr
    public static void SetStatusCaptionNr(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("StatusCaptionNr", value);
    }

/// Gets StatusCaptionNr
    public static short GetStatusCaptionNr(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("StatusCaptionNr");
    }

/// Sets SortDescending
    public static void SetSortDescending(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("SortDescending", value);
    }

/// Gets SortDescending
    public static bool GetSortDescending(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("SortDescending");
    }

/// Sets ComesAnz
    public static void SetComesAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ComesAnz", value);
    }

/// Gets ComesAnz
    public static short GetComesAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ComesAnz");
    }

/// Sets GoesAnz
    public static void SetGoesAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("GoesAnz", value);
    }

/// Gets GoesAnz
    public static short GetGoesAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("GoesAnz");
    }

/// Sets QuitAnz
    public static void SetQuitAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("QuitAnz", value);
    }

/// Gets QuitAnz
    public static short GetQuitAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("QuitAnz");
    }

/// Sets ReactionTimeAnz
    public static void SetReactionTimeAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ReactionTimeAnz", value);
    }

/// Gets ReactionTimeAnz
    public static short GetReactionTimeAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ReactionTimeAnz");
    }

/// Sets ReactionCountAnz
    public static void SetReactionCountAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ReactionCountAnz", value);
    }

/// Gets ReactionCountAnz
    public static short GetReactionCountAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ReactionCountAnz");
    }

/// Sets ReactionStatAnz
    public static void SetReactionStatAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ReactionStatAnz", value);
    }

/// Gets ReactionStatAnz
    public static short GetReactionStatAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ReactionStatAnz");
    }

/// Sets TimeLastingAnz
    public static void SetTimeLastingAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("TimeLastingAnz", value);
    }

/// Gets TimeLastingAnz
    public static short GetTimeLastingAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("TimeLastingAnz");
    }

/// Sets GroupsSymbol
    public static void SetGroupsSymbol(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("GroupsSymbol", value);
    }

/// Gets GroupsSymbol
    public static string GetGroupsSymbol(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("GroupsSymbol");
    }

/// Sets GroupSymbolAnz
    public static void SetGroupSymbolAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("GroupSymbolAnz", value);
    }

/// Gets GroupSymbolAnz
    public static short GetGroupSymbolAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("GroupSymbolAnz");
    }

/// Sets GroupSymbolStyle
    public static void SetGroupSymbolStyle(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("GroupSymbolStyle", value);
    }

/// Gets GroupSymbolStyle
    public static short GetGroupSymbolStyle(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("GroupSymbolStyle");
    }

/// Sets ResourceLabel
    public static void SetResourceLabel(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ResourceLabel", value);
    }

/// Gets ResourceLabel
    public static string GetResourceLabel(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ResourceLabel");
    }

/// Sets ResourceLabelAnz
    public static void SetResourceLabelAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ResourceLabelAnz", value);
    }

/// Gets ResourceLabelAnz
    public static short GetResourceLabelAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ResourceLabelAnz");
    }

/// Sets Area
    public static void SetArea(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Area", value);
    }

/// Gets Area
    public static string GetArea(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Area");
    }

/// Sets AreaAnz
    public static void SetAreaAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("AreaAnz", value);
    }

/// Gets AreaAnz
    public static short GetAreaAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("AreaAnz");
    }

/// Sets AreaNr
    public static void SetAreaNr(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("AreaNr", value);
    }

/// Gets AreaNr
    public static string GetAreaNr(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("AreaNr");
    }

/// Sets AreaNrAnz
    public static void SetAreaNrAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("AreaNrAnz", value);
    }

/// Gets AreaNrAnz
    public static short GetAreaNrAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("AreaNrAnz");
    }

/// Sets ClassSymbol
    public static void SetClassSymbol(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ClassSymbol", value);
    }

/// Gets ClassSymbol
    public static string GetClassSymbol(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ClassSymbol");
    }

/// Sets ClassSymbolAnz
    public static void SetClassSymbolAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ClassSymbolAnz", value);
    }

/// Gets ClassSymbolAnz
    public static short GetClassSymbolAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ClassSymbolAnz");
    }

/// Sets ClassSymbolStyle
    public static void SetClassSymbolStyle(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ClassSymbolStyle", value);
    }

/// Gets ClassSymbolStyle
    public static short GetClassSymbolStyle(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ClassSymbolStyle");
    }

/// Sets Unit
    public static void SetUnit(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Unit", value);
    }

/// Gets Unit
    public static string GetUnit(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Unit");
    }

/// Sets UnitAnz
    public static void SetUnitAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("UnitAnz", value);
    }

/// Gets UnitAnz
    public static short GetUnitAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("UnitAnz");
    }

/// Sets Cause
    public static void SetCause(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Cause", value);
    }

/// Gets Cause
    public static string GetCause(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Cause");
    }

/// Sets CauseAnz
    public static void SetCauseAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("CauseAnz", value);
    }

/// Gets CauseAnz
    public static short GetCauseAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("CauseAnz");
    }

/// Sets CauseGuid
    public static void SetCauseGuid(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("CauseGuid", value);
    }

/// Gets CauseGuid
    public static string GetCauseGuid(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("CauseGuid");
    }

/// Sets CauseGuidAnz
    public static void SetCauseGuidAnz(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("CauseGuidAnz", value);
    }

/// Gets CauseGuidAnz
    public static short GetCauseGuidAnz(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("CauseGuidAnz");
    }

/// Sets StatusStyle
    public static void SetStatusStyle(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("StatusStyle", value);
    }

/// Gets StatusStyle
    public static short GetStatusStyle(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("StatusStyle");
    }

/// Sets LeavingTimeIntern
    public static void SetLeavingTimeIntern(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("LeavingTimeIntern", value);
    }

/// Gets LeavingTimeIntern
    public static string GetLeavingTimeIntern(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("LeavingTimeIntern");
    }

/// Sets LeavingTimeExtern
    public static void SetLeavingTimeExtern(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("LeavingTimeExtern", value);
    }

/// Gets LeavingTimeExtern
    public static string GetLeavingTimeExtern(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("LeavingTimeExtern");
    }

/// Sets ComingTimeIntern
    public static void SetComingTimeIntern(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ComingTimeIntern", value);
    }

/// Gets ComingTimeIntern
    public static string GetComingTimeIntern(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ComingTimeIntern");
    }

/// Sets ComingTimeExtern
    public static void SetComingTimeExtern(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ComingTimeExtern", value);
    }

/// Gets ComingTimeExtern
    public static string GetComingTimeExtern(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ComingTimeExtern");
    }

/// Sets ReactivationTimeIntern
    public static void SetReactivationTimeIntern(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ReactivationTimeIntern", value);
    }

/// Gets ReactivationTimeIntern
    public static string GetReactivationTimeIntern(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ReactivationTimeIntern");
    }

/// Sets ReactivationTimeExtern
    public static void SetReactivationTimeExtern(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ReactivationTimeExtern", value);
    }

/// Gets ReactivationTimeExtern
    public static string GetReactivationTimeExtern(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ReactivationTimeExtern");
    }

/// Sets LeavingTimeInternWidth
    public static void SetLeavingTimeInternWidth(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("LeavingTimeInternWidth", value);
    }

/// Gets LeavingTimeInternWidth
    public static short GetLeavingTimeInternWidth(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("LeavingTimeInternWidth");
    }

/// Sets LeavingTimeExternWidth
    public static void SetLeavingTimeExternWidth(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("LeavingTimeExternWidth", value);
    }

/// Gets LeavingTimeExternWidth
    public static short GetLeavingTimeExternWidth(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("LeavingTimeExternWidth");
    }

/// Sets ComingTimeInternWidth
    public static void SetComingTimeInternWidth(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ComingTimeInternWidth", value);
    }

/// Gets ComingTimeInternWidth
    public static short GetComingTimeInternWidth(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ComingTimeInternWidth");
    }

/// Sets ComingTimeExternWidth
    public static void SetComingTimeExternWidth(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ComingTimeExternWidth", value);
    }

/// Gets ComingTimeExternWidth
    public static short GetComingTimeExternWidth(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ComingTimeExternWidth");
    }

/// Sets ReactivationTimeInternWidth
    public static void SetReactivationTimeInternWidth(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ReactivationTimeInternWidth", value);
    }

/// Gets ReactivationTimeInternWidth
    public static short GetReactivationTimeInternWidth(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ReactivationTimeInternWidth");
    }

/// Sets ReactivationTimeExternWidth
    public static void SetReactivationTimeExternWidth(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ReactivationTimeExternWidth", value);
    }

/// Gets ReactivationTimeExternWidth
    public static short GetReactivationTimeExternWidth(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ReactivationTimeExternWidth");
    }

/// Sets EquipmentModelGroupWidth
    public static void SetEquipmentModelGroupWidth(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("EquipmentModelGroupWidth", value);
    }

/// Gets EquipmentModelGroupWidth
    public static short GetEquipmentModelGroupWidth(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("EquipmentModelGroupWidth");
    }

/// Sets EquipmentModelGroup
    public static void SetEquipmentModelGroup(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("EquipmentModelGroup", value);
    }

/// Gets EquipmentModelGroup
    public static string GetEquipmentModelGroup(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("EquipmentModelGroup");
    }

/// Sets SystemModel
    public static void SetSystemModel(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("SystemModel", value);
    }

/// Gets SystemModel
    public static string GetSystemModel(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("SystemModel");
    }

/// Sets InternExternTimeDifference
    public static void SetInternExternTimeDifference(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("InternExternTimeDifference", value);
    }

/// Gets InternExternTimeDifference
    public static string GetInternExternTimeDifference(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("InternExternTimeDifference");
    }

/// Sets InternExternTimeDifferenceWidth
    public static void SetInternExternTimeDifferenceWidth(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("InternExternTimeDifferenceWidth", value);
    }

/// Gets InternExternTimeDifferenceWidth
    public static short GetInternExternTimeDifferenceWidth(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("InternExternTimeDifferenceWidth");
    }

/// Sets AmlLastModifyTitle
    public static void SetAmlLastModifyTitle(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("AmlLastModifyTitle", value);
    }

/// Gets AmlLastModifyTitle
    public static string GetAmlLastModifyTitle(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("AmlLastModifyTitle");
    }

/// Sets AmlLastModifyTitleWidth
    public static void SetAmlLastModifyTitleWidth(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("AmlLastModifyTitleWidth", value);
    }

/// Gets AmlLastModifyTitleWidth
    public static short GetAmlLastModifyTitleWidth(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("AmlLastModifyTitleWidth");
    }

/// Sets CategoryTitle
    public static void SetCategoryTitle(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("CategoryTitle", value);
    }

/// Gets CategoryTitle
    public static string GetCategoryTitle(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("CategoryTitle");
    }

/// Sets CategoryTitleWidth
    public static void SetCategoryTitleWidth(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("CategoryTitleWidth", value);
    }

/// Gets CategoryTitleWidth
    public static short GetCategoryTitleWidth(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("CategoryTitleWidth");
    }

/// Sets ExportColumnsMode
    public static void SetExportColumnsMode(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ExportColumnsMode", value);
    }

/// Gets ExportColumnsMode
    public static short GetExportColumnsMode(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ExportColumnsMode");
    }

/// Sets ExternalReferenceCount
    public static void SetExternalReferenceCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("ExternalReferenceCount", value);
    }

/// Gets ExternalReferenceCount
    public static short GetExternalReferenceCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("ExternalReferenceCount");
    }

/// Sets DescriptionCount
    public static void SetDescriptionCount(this IChronologicalEventList cel, short value)
    {
      cel.SetDynamicProperty("DescriptionCount", value);
    }

/// Gets DescriptionCount
    public static short GetDescriptionCount(this IChronologicalEventList cel)
    {
      return (short) cel.GetDynamicProperty("DescriptionCount");
    }

/// Sets ExternalReference
    public static void SetExternalReference(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("ExternalReference", value);
    }

/// Gets ExternalReference
    public static string GetExternalReference(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("ExternalReference");
    }

/// Sets Description
    public static void SetDescription(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Description", value);
    }

/// Gets Description
    public static string GetDescription(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Description");
    }

/// Sets Column
    public static void SetColumn(this IChronologicalEventList cel, object value)
    {
      cel.SetDynamicProperty("Column", value);
    }

/// Gets Column
    public static object GetColumn(this IChronologicalEventList cel)
    {
      return (object) cel.GetDynamicProperty("Column");
    }

/// Sets IsFilterActive
    public static void SetIsFilterActive(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsFilterActive", value);
    }

/// Gets IsFilterActive
    public static bool GetIsFilterActive(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsFilterActive");
    }

/// Sets IsSubFind
    public static void SetIsSubFind(this IChronologicalEventList cel, bool value)
    {
      cel.SetDynamicProperty("IsSubFind", value);
    }

/// Gets IsSubFind
    public static bool GetIsSubFind(this IChronologicalEventList cel)
    {
      return (bool) cel.GetDynamicProperty("IsSubFind");
    }

/// Sets Condition
    public static void SetCondition(this IChronologicalEventList cel, ushort value)
    {
      cel.SetDynamicProperty("Condition", value);
    }

/// Gets Condition
    public static ushort GetCondition(this IChronologicalEventList cel)
    {
      return (ushort) cel.GetDynamicProperty("Condition");
    }

/// Sets Expression
    public static void SetExpression(this IChronologicalEventList cel, string value)
    {
      cel.SetDynamicProperty("Expression", value);
    }

/// Gets Expression
    public static string GetExpression(this IChronologicalEventList cel)
    {
      return (string) cel.GetDynamicProperty("Expression");
    }

/// Sets StatusMask
    public static void SetStatusMask(this IChronologicalEventList cel, ulong value)
    {
      cel.SetDynamicProperty("StatusMask", value);
    }

/// Gets StatusMask
    public static ulong GetStatusMask(this IChronologicalEventList cel)
    {
      return (ulong) cel.GetDynamicProperty("StatusMask");
    }

  }
}