//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.ScreenElement;

namespace zenonExtensions
{
  public static class ControlElementExtension
  {
/// Sets MenuID
    public static void SetMenuID(this IControlElement mdiElement, uint value)
    {
      mdiElement.SetDynamicProperty("MenuID", value);
    }

/// Gets MenuID
    public static uint GetMenuID(this IControlElement mdiElement)
    {
      return (uint) mdiElement.GetDynamicProperty("MenuID");
    }

/// Sets Default
    public static void SetDefault(this IControlElement mdiElement, bool value)
    {
      mdiElement.SetDynamicProperty("Default", value);
    }

/// Gets Default
    public static bool GetDefault(this IControlElement mdiElement)
    {
      return (bool) mdiElement.GetDynamicProperty("Default");
    }

/// Sets Type
    public static void SetType(this IControlElement mdiElement, ushort value)
    {
      mdiElement.SetDynamicProperty("Type", value);
    }

/// Gets Type
    public static ushort GetType(this IControlElement mdiElement)
    {
      return (ushort) mdiElement.GetDynamicProperty("Type");
    }

/// Sets ID
    public static void SetID(this IControlElement mdiElement, int value)
    {
      mdiElement.SetDynamicProperty("ID", value);
    }

/// Gets ID
    public static int GetID(this IControlElement mdiElement)
    {
      return (int) mdiElement.GetDynamicProperty("ID");
    }

/// Sets Text
    public static void SetText(this IControlElement mdiElement, string value)
    {
      mdiElement.SetDynamicProperty("Text", value);
    }

/// Gets Text
    public static string GetText(this IControlElement mdiElement)
    {
      return (string) mdiElement.GetDynamicProperty("Text");
    }

/// Sets Style
    public static void SetStyle(this IControlElement mdiElement, uint value)
    {
      mdiElement.SetDynamicProperty("Style", value);
    }

/// Gets Style
    public static uint GetStyle(this IControlElement mdiElement)
    {
      return (uint) mdiElement.GetDynamicProperty("Style");
    }

/// Sets StyleMask
    public static void SetStyleMask(this IControlElement mdiElement, uint value)
    {
      mdiElement.SetDynamicProperty("StyleMask", value);
    }

/// Gets StyleMask
    public static uint GetStyleMask(this IControlElement mdiElement)
    {
      return (uint) mdiElement.GetDynamicProperty("StyleMask");
    }

/// Sets TextColor
    public static void SetTextColor(this IControlElement mdiElement, uint value)
    {
      mdiElement.SetDynamicProperty("TextColor", value);
    }

/// Gets TextColor
    public static uint GetTextColor(this IControlElement mdiElement)
    {
      return (uint) mdiElement.GetDynamicProperty("TextColor");
    }

/// Sets BackColor
    public static void SetBackColor(this IControlElement mdiElement, uint value)
    {
      mdiElement.SetDynamicProperty("BackColor", value);
    }

/// Gets BackColor
    public static uint GetBackColor(this IControlElement mdiElement)
    {
      return (uint) mdiElement.GetDynamicProperty("BackColor");
    }

/// Sets Info
    public static void SetInfo(this IControlElement mdiElement, uint value)
    {
      mdiElement.SetDynamicProperty("Info", value);
    }

/// Gets Info
    public static uint GetInfo(this IControlElement mdiElement)
    {
      return (uint) mdiElement.GetDynamicProperty("Info");
    }

/// Sets Top
    public static void SetTop(this IControlElement mdiElement, int value)
    {
      mdiElement.SetDynamicProperty("Top", value);
    }

/// Gets Top
    public static int GetTop(this IControlElement mdiElement)
    {
      return (int) mdiElement.GetDynamicProperty("Top");
    }

/// Sets Left
    public static void SetLeft(this IControlElement mdiElement, int value)
    {
      mdiElement.SetDynamicProperty("Left", value);
    }

/// Gets Left
    public static int GetLeft(this IControlElement mdiElement)
    {
      return (int) mdiElement.GetDynamicProperty("Left");
    }

/// Sets Height
    public static void SetHeight(this IControlElement mdiElement, int value)
    {
      mdiElement.SetDynamicProperty("Height", value);
    }

/// Gets Height
    public static int GetHeight(this IControlElement mdiElement)
    {
      return (int) mdiElement.GetDynamicProperty("Height");
    }

/// Sets Width
    public static void SetWidth(this IControlElement mdiElement, int value)
    {
      mdiElement.SetDynamicProperty("Width", value);
    }

/// Gets Width
    public static int GetWidth(this IControlElement mdiElement)
    {
      return (int) mdiElement.GetDynamicProperty("Width");
    }

  }
}