//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.EquipmentModeling;

namespace zenonExtensions
{
  public static class EquipmentModelingExtension
  {
/// Sets Modules
    public static void SetModules(this IEquipmentModeling systemModelManager, object value)
    {
      systemModelManager.SetDynamicProperty("Modules", value);
    }

/// Gets Modules
    public static object GetModules(this IEquipmentModeling systemModelManager)
    {
      return (object) systemModelManager.GetDynamicProperty("Modules");
    }

  }
}