//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.FontList;

namespace zenonExtensions
{
  public static class FontExtension
  {
/// Sets Name
    public static void SetName(this IFont fontItem, string value)
    {
      fontItem.SetDynamicProperty("Name", value);
    }

/// Gets Name
    public static string GetName(this IFont fontItem)
    {
      return (string) fontItem.GetDynamicProperty("Name");
    }

/// Sets Font
    public static void SetFont(this IFont fontItem, string value)
    {
      fontItem.SetDynamicProperty("Font", value);
    }

/// Gets Font
    public static string GetFont(this IFont fontItem)
    {
      return (string) fontItem.GetDynamicProperty("Font");
    }

/// Sets Number
    public static void SetNumber(this IFont fontItem, ushort value)
    {
      fontItem.SetDynamicProperty("Number", value);
    }

/// Gets Number
    public static ushort GetNumber(this IFont fontItem)
    {
      return (ushort) fontItem.GetDynamicProperty("Number");
    }

  }
}