//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.FontList;

namespace zenonExtensions
{
  public static class FontListExtension
  {
/// Sets Name
    public static void SetName(this IFontList fontList, string value)
    {
      fontList.SetDynamicProperty("Name", value);
    }

/// Gets Name
    public static string GetName(this IFontList fontList)
    {
      return (string) fontList.GetDynamicProperty("Name");
    }

  }
}