//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.Menu;

namespace zenonExtensions
{
  public static class MenuItemExtension
  {
/// Sets Interlocking
    public static void SetLocking(this IMenuItem zenMenuItem, uint value)
    {
      zenMenuItem.SetDynamicProperty("Locking", value);
    }

/// Gets Interlocking
    public static uint GetLocking(this IMenuItem zenMenuItem)
    {
      return (uint) zenMenuItem.GetDynamicProperty("Locking");
    }

/// Sets Apply authorization properties from variable
    public static void SetRightsPropertiesFromVariable(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("RightsPropertiesFromVariable", value);
    }

/// Gets Apply authorization properties from variable
    public static bool GetRightsPropertiesFromVariable(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("RightsPropertiesFromVariable");
    }

/// Sets Authorization/Perform level
    public static void SetPassword(this IMenuItem zenMenuItem, short value)
    {
      zenMenuItem.SetDynamicProperty("Password", value);
    }

/// Gets Authorization/Perform level
    public static short GetPassword(this IMenuItem zenMenuItem)
    {
      return (short) zenMenuItem.GetDynamicProperty("Password");
    }

/// Sets Signature necessary
    public static void SetSignatureMode(this IMenuItem zenMenuItem, ushort value)
    {
      zenMenuItem.SetDynamicProperty("SignatureMode", value);
    }

/// Gets Signature necessary
    public static ushort GetSignatureMode(this IMenuItem zenMenuItem)
    {
      return (ushort) zenMenuItem.GetDynamicProperty("SignatureMode");
    }

/// Sets Signature
    public static void SetSignature(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("Signature", value);
    }

/// Gets Signature
    public static bool GetSignature(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("Signature");
    }

/// Sets Level for "Verify"
    public static void SeteSignatureVerificationLevel(this IMenuItem zenMenuItem, ushort value)
    {
      zenMenuItem.SetDynamicProperty("eSignatureVerificationLevel", value);
    }

/// Gets Level for "Verify"
    public static ushort GeteSignatureVerificationLevel(this IMenuItem zenMenuItem)
    {
      return (ushort) zenMenuItem.GetDynamicProperty("eSignatureVerificationLevel");
    }

/// Sets Level for "Approve"
    public static void SeteSignatureApprobationLevel(this IMenuItem zenMenuItem, ushort value)
    {
      zenMenuItem.SetDynamicProperty("eSignatureApprobationLevel", value);
    }

/// Gets Level for "Approve"
    public static ushort GeteSignatureApprobationLevel(this IMenuItem zenMenuItem)
    {
      return (ushort) zenMenuItem.GetDynamicProperty("eSignatureApprobationLevel");
    }

/// Sets Comment for "Perform" required
    public static void SeteSignatureCommentRequiredForPerform(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("eSignatureCommentRequiredForPerform", value);
    }

/// Gets Comment for "Perform" required
    public static bool GeteSignatureCommentRequiredForPerform(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("eSignatureCommentRequiredForPerform");
    }

/// Sets Comment for "Verify" required
    public static void SeteSignatureCommentRequiredForVerify(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("eSignatureCommentRequiredForVerify", value);
    }

/// Gets Comment for "Verify" required
    public static bool GeteSignatureCommentRequiredForVerify(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("eSignatureCommentRequiredForVerify");
    }

/// Sets Comment for "Approve" required
    public static void SeteSignatureCommentRequiredForApprove(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("eSignatureCommentRequiredForApprove", value);
    }

/// Gets Comment for "Approve" required
    public static bool GeteSignatureCommentRequiredForApprove(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("eSignatureCommentRequiredForApprove");
    }

/// Sets Signature text
    public static void SetSignatureText(this IMenuItem zenMenuItem, string value)
    {
      zenMenuItem.SetDynamicProperty("SignatureText", value);
    }

/// Gets Signature text
    public static string GetSignatureText(this IMenuItem zenMenuItem)
    {
      return (string) zenMenuItem.GetDynamicProperty("SignatureText");
    }

/// Sets Signature text editable
    public static void SetSignatureEditModus(this IMenuItem zenMenuItem, short value)
    {
      zenMenuItem.SetDynamicProperty("SignatureEditModus", value);
    }

/// Gets Signature text editable
    public static short GetSignatureEditModus(this IMenuItem zenMenuItem)
    {
      return (short) zenMenuItem.GetDynamicProperty("SignatureEditModus");
    }

/// Sets eSignature process description
    public static void SeteSignatureProcessDescription(this IMenuItem zenMenuItem, string value)
    {
      zenMenuItem.SetDynamicProperty("eSignatureProcessDescription", value);
    }

/// Gets eSignature process description
    public static string GeteSignatureProcessDescription(this IMenuItem zenMenuItem)
    {
      return (string) zenMenuItem.GetDynamicProperty("eSignatureProcessDescription");
    }

/// Sets Text
    public static void SetCaption(this IMenuItem zenMenuItem, string value)
    {
      zenMenuItem.SetDynamicProperty("Caption", value);
    }

/// Gets Text
    public static string GetCaption(this IMenuItem zenMenuItem)
    {
      return (string) zenMenuItem.GetDynamicProperty("Caption");
    }

/// Sets Menu ID
    public static void SetName(this IMenuItem zenMenuItem, string value)
    {
      zenMenuItem.SetDynamicProperty("Name", value);
    }

/// Gets Menu ID
    public static string GetName(this IMenuItem zenMenuItem)
    {
      return (string) zenMenuItem.GetDynamicProperty("Name");
    }

/// Sets Graphics File
    public static void SetPicture(this IMenuItem zenMenuItem, string value)
    {
      zenMenuItem.SetDynamicProperty("Picture", value);
    }

/// Gets Graphics File
    public static string GetPicture(this IMenuItem zenMenuItem)
    {
      return (string) zenMenuItem.GetDynamicProperty("Picture");
    }

/// Sets Active
    public static void SetEnabled(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("Enabled", value);
    }

/// Gets Active
    public static bool GetEnabled(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("Enabled");
    }

/// Sets Action type
    public static void SetType(this IMenuItem zenMenuItem, short value)
    {
      zenMenuItem.SetDynamicProperty("Type", value);
    }

/// Gets Action type
    public static short GetType(this IMenuItem zenMenuItem)
    {
      return (short) zenMenuItem.GetDynamicProperty("Type");
    }

/// Sets visible
    public static void SetVisible(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("Visible", value);
    }

/// Gets visible
    public static bool GetVisible(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("Visible");
    }

/// Sets Check mark
    public static void SetChecked(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("Checked", value);
    }

/// Gets Check mark
    public static bool GetChecked(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("Checked");
    }

/// Sets Submenu
    public static void SetPopup_Menu(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("Popup_Menu", value);
    }

/// Gets Submenu
    public static bool GetPopup_Menu(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("Popup_Menu");
    }

/// Sets Separator active
    public static void SetSeperator(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("Seperator", value);
    }

/// Gets Separator active
    public static bool GetSeperator(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("Seperator");
    }

/// Sets Width
    public static void SetSeparatorWidth(this IMenuItem zenMenuItem, byte value)
    {
      zenMenuItem.SetDynamicProperty("SeparatorWidth", value);
    }

/// Gets Width
    public static byte GetSeparatorWidth(this IMenuItem zenMenuItem)
    {
      return (byte) zenMenuItem.GetDynamicProperty("SeparatorWidth");
    }

/// Sets Color
    public static void SetSeparatorColor(this IMenuItem zenMenuItem, uint value)
    {
      zenMenuItem.SetDynamicProperty("SeparatorColor", value);
    }

/// Gets Color
    public static uint GetSeparatorColor(this IMenuItem zenMenuItem)
    {
      return (uint) zenMenuItem.GetDynamicProperty("SeparatorColor");
    }

/// Sets Graphics File
    public static void SetBackgroundPicture(this IMenuItem zenMenuItem, string value)
    {
      zenMenuItem.SetDynamicProperty("BackgroundPicture", value);
    }

/// Gets Graphics File
    public static string GetBackgroundPicture(this IMenuItem zenMenuItem)
    {
      return (string) zenMenuItem.GetDynamicProperty("BackgroundPicture");
    }

/// Sets Alignment
    public static void SetBackgroundPicRepres(this IMenuItem zenMenuItem, short value)
    {
      zenMenuItem.SetDynamicProperty("BackgroundPicRepres", value);
    }

/// Gets Alignment
    public static short GetBackgroundPicRepres(this IMenuItem zenMenuItem)
    {
      return (short) zenMenuItem.GetDynamicProperty("BackgroundPicRepres");
    }

/// Sets File
    public static void SetHelpFile(this IMenuItem zenMenuItem, string value)
    {
      zenMenuItem.SetDynamicProperty("HelpFile", value);
    }

/// Gets File
    public static string GetHelpFile(this IMenuItem zenMenuItem)
    {
      return (string) zenMenuItem.GetDynamicProperty("HelpFile");
    }

/// Sets Chapter
    public static void SetHelpCapture(this IMenuItem zenMenuItem, string value)
    {
      zenMenuItem.SetDynamicProperty("HelpCapture", value);
    }

/// Gets Chapter
    public static string GetHelpCapture(this IMenuItem zenMenuItem)
    {
      return (string) zenMenuItem.GetDynamicProperty("HelpCapture");
    }

/// Sets VBA macro
    public static void SetVBA_Macro(this IMenuItem zenMenuItem, uint value)
    {
      zenMenuItem.SetDynamicProperty("VBA_Macro", value);
    }

/// Gets VBA macro
    public static uint GetVBA_Macro(this IMenuItem zenMenuItem)
    {
      return (uint) zenMenuItem.GetDynamicProperty("VBA_Macro");
    }

/// Sets Variable from element
    public static void SetFromElem(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("FromElem", value);
    }

/// Gets Variable from element
    public static bool GetFromElem(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("FromElem");
    }

/// Sets Variable
    public static void SetVariable(this IMenuItem zenMenuItem, object value)
    {
      zenMenuItem.SetDynamicProperty("Variable", value);
    }

/// Gets Variable
    public static object GetVariable(this IMenuItem zenMenuItem)
    {
      return (object) zenMenuItem.GetDynamicProperty("Variable");
    }

/// Sets Dialog
    public static void SetSWDialog(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("SWDialog", value);
    }

/// Gets Dialog
    public static bool GetSWDialog(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("SWDialog");
    }

/// Sets Propose current value
    public static void SetActValue(this IMenuItem zenMenuItem, bool value)
    {
      zenMenuItem.SetDynamicProperty("ActValue", value);
    }

/// Gets Propose current value
    public static bool GetActValue(this IMenuItem zenMenuItem)
    {
      return (bool) zenMenuItem.GetDynamicProperty("ActValue");
    }

/// Sets Write set value/Change by
    public static void SetSollwert(this IMenuItem zenMenuItem, double value)
    {
      zenMenuItem.SetDynamicProperty("Sollwert", value);
    }

/// Gets Write set value/Change by
    public static double GetSollwert(this IMenuItem zenMenuItem)
    {
      return (double) zenMenuItem.GetDynamicProperty("Sollwert");
    }

/// Sets Screen
    public static void SetScreen(this IMenuItem zenMenuItem, string value)
    {
      zenMenuItem.SetDynamicProperty("Screen", value);
    }

/// Gets Screen
    public static string GetScreen(this IMenuItem zenMenuItem)
    {
      return (string) zenMenuItem.GetDynamicProperty("Screen");
    }

/// Sets Time filter relative
    public static void SetRelativeTimeFilter(this IMenuItem zenMenuItem, string value)
    {
      zenMenuItem.SetDynamicProperty("RelativeTimeFilter", value);
    }

/// Gets Time filter relative
    public static string GetRelativeTimeFilter(this IMenuItem zenMenuItem)
    {
      return (string) zenMenuItem.GetDynamicProperty("RelativeTimeFilter");
    }

/// Sets Refresh rate
    public static void SetRefreshrate(this IMenuItem zenMenuItem, float value)
    {
      zenMenuItem.SetDynamicProperty("Refreshrate", value);
    }

/// Gets Refresh rate
    public static float GetRefreshrate(this IMenuItem zenMenuItem)
    {
      return (float) zenMenuItem.GetDynamicProperty("Refreshrate");
    }

/// Sets Style group chart
    public static void SetDiagramStyle(this IMenuItem zenMenuItem, System.Guid value)
    {
      zenMenuItem.SetDynamicProperty("DiagramStyle", value);
    }

/// Gets Style group chart
    public static System.Guid GetDiagramStyle(this IMenuItem zenMenuItem)
    {
      return (System.Guid) zenMenuItem.GetDynamicProperty("DiagramStyle");
    }

  }
}