//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.RecipeGroupManager;

namespace zenonExtensions
{
  public static class RecipeValueExtension
  {
/// Sets Action
    public static void SetType(this IRecipeValue rGMRecipeValue, uint value)
    {
      rGMRecipeValue.SetDynamicProperty("Type", value);
    }

/// Gets Action
    public static uint GetType(this IRecipeValue rGMRecipeValue)
    {
      return (uint) rGMRecipeValue.GetDynamicProperty("Type");
    }

/// Sets Variable
    public static void SetVariable(this IRecipeValue rGMRecipeValue, object value)
    {
      rGMRecipeValue.SetDynamicProperty("Variable", value);
    }

/// Gets Variable
    public static object GetVariable(this IRecipeValue rGMRecipeValue)
    {
      return (object) rGMRecipeValue.GetDynamicProperty("Variable");
    }

/// Sets Offset
    public static void SetOffset(this IRecipeValue rGMRecipeValue, int value)
    {
      rGMRecipeValue.SetDynamicProperty("Offset", value);
    }

/// Gets Offset
    public static int GetOffset(this IRecipeValue rGMRecipeValue)
    {
      return (int) rGMRecipeValue.GetDynamicProperty("Offset");
    }

/// Sets Source variable
    public static void SetSourceVar(this IRecipeValue rGMRecipeValue, object value)
    {
      rGMRecipeValue.SetDynamicProperty("SourceVar", value);
    }

/// Gets Source variable
    public static object GetSourceVar(this IRecipeValue rGMRecipeValue)
    {
      return (object) rGMRecipeValue.GetDynamicProperty("SourceVar");
    }

/// Sets SourceOffset
    public static void SetSourceOffset(this IRecipeValue rGMRecipeValue, int value)
    {
      rGMRecipeValue.SetDynamicProperty("SourceOffset", value);
    }

/// Gets SourceOffset
    public static int GetSourceOffset(this IRecipeValue rGMRecipeValue)
    {
      return (int) rGMRecipeValue.GetDynamicProperty("SourceOffset");
    }

/// Sets Value or variable
    public static void SetValue(this IRecipeValue rGMRecipeValue, double value)
    {
      rGMRecipeValue.SetDynamicProperty("Value", value);
    }

/// Gets Value or variable
    public static double GetValue(this IRecipeValue rGMRecipeValue)
    {
      return (double) rGMRecipeValue.GetDynamicProperty("Value");
    }

/// Sets StringValue
    public static void SetStringValue(this IRecipeValue rGMRecipeValue, string value)
    {
      rGMRecipeValue.SetDynamicProperty("StringValue", value);
    }

/// Gets StringValue
    public static string GetStringValue(this IRecipeValue rGMRecipeValue)
    {
      return (string) rGMRecipeValue.GetDynamicProperty("StringValue");
    }

/// Sets Variable name
    public static void SetZValue(this IRecipeValue rGMRecipeValue, double value)
    {
      rGMRecipeValue.SetDynamicProperty("ZValue", value);
    }

/// Gets Variable name
    public static double GetZValue(this IRecipeValue rGMRecipeValue)
    {
      return (double) rGMRecipeValue.GetDynamicProperty("ZValue");
    }

  }
}