//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.RecipeGroupManager;

namespace zenonExtensions
{
  public static class RecipeGroupExtension
  {
/// Sets Group name
    public static void SetName(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Name", value);
    }

/// Gets Group name
    public static string GetName(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Name");
    }

/// Sets Equipment Groups
    public static void SetSystemModelGroup(this IRecipeGroup rGMRecipeGroup, object value)
    {
      rGMRecipeGroup.SetDynamicProperty("SystemModelGroup", value);
    }

/// Gets Equipment Groups
    public static object GetSystemModelGroup(this IRecipeGroup rGMRecipeGroup)
    {
      return (object) rGMRecipeGroup.GetDynamicProperty("SystemModelGroup");
    }

/// Sets Write synchronously
    public static void SetWriteSync(this IRecipeGroup rGMRecipeGroup, bool value)
    {
      rGMRecipeGroup.SetDynamicProperty("WriteSync", value);
    }

/// Gets Write synchronously
    public static bool GetWriteSync(this IRecipeGroup rGMRecipeGroup)
    {
      return (bool) rGMRecipeGroup.GetDynamicProperty("WriteSync");
    }

/// Sets Timeout [ms]
    public static void SetWriteTimeout(this IRecipeGroup rGMRecipeGroup, uint value)
    {
      rGMRecipeGroup.SetDynamicProperty("WriteTimeout", value);
    }

/// Gets Timeout [ms]
    public static uint GetWriteTimeout(this IRecipeGroup rGMRecipeGroup)
    {
      return (uint) rGMRecipeGroup.GetDynamicProperty("WriteTimeout");
    }

/// Sets Smart Object
    public static void SetSOSourceName(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("SOSourceName", value);
    }

/// Gets Smart Object
    public static string GetSOSourceName(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("SOSourceName");
    }

/// Sets Recipe writing complete
    public static void SetFeedback_Write_Result(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Result", value);
    }

/// Gets Recipe writing complete
    public static string GetFeedback_Write_Result(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Result");
    }

/// Sets Recipe name
    public static void SetFeedback_Write_Name(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Name", value);
    }

/// Gets Recipe name
    public static string GetFeedback_Write_Name(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Name");
    }

/// Sets Recipe number
    public static void SetFeedback_Write_Number(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Number", value);
    }

/// Gets Recipe number
    public static string GetFeedback_Write_Number(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Number");
    }

/// Sets Recipe version
    public static void SetFeedback_Write_Version(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Version", value);
    }

/// Gets Recipe version
    public static string GetFeedback_Write_Version(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Version");
    }

/// Sets Authorization level
    public static void SetFeedback_Write_Rights(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Rights", value);
    }

/// Gets Authorization level
    public static string GetFeedback_Write_Rights(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Rights");
    }

/// Sets Recipe status text
    public static void SetFeedback_Write_Status_Txt(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Status_Txt", value);
    }

/// Gets Recipe status text
    public static string GetFeedback_Write_Status_Txt(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Status_Txt");
    }

/// Sets Recipe status number
    public static void SetFeedback_Write_Status_Nr(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Status_Nr", value);
    }

/// Gets Recipe status number
    public static string GetFeedback_Write_Status_Nr(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Status_Nr");
    }

/// Sets Change user
    public static void SetFeedback_Write_Userchange(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Userchange", value);
    }

/// Gets Change user
    public static string GetFeedback_Write_Userchange(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Userchange");
    }

/// Sets Change time
    public static void SetFeedback_Write_Timechange(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Timechange", value);
    }

/// Gets Change time
    public static string GetFeedback_Write_Timechange(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Timechange");
    }

/// Sets Comment 1
    public static void SetFeedback_Write_Comment1(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Comment1", value);
    }

/// Gets Comment 1
    public static string GetFeedback_Write_Comment1(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Comment1");
    }

/// Sets Comment 2
    public static void SetFeedback_Write_Comment2(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Comment2", value);
    }

/// Gets Comment 2
    public static string GetFeedback_Write_Comment2(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Comment2");
    }

/// Sets Comment 3
    public static void SetFeedback_Write_Comment3(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Comment3", value);
    }

/// Gets Comment 3
    public static string GetFeedback_Write_Comment3(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Comment3");
    }

/// Sets Comment 4
    public static void SetFeedback_Write_Comment4(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Comment4", value);
    }

/// Gets Comment 4
    public static string GetFeedback_Write_Comment4(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Comment4");
    }

/// Sets Comment 5
    public static void SetFeedback_Write_Comment5(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Comment5", value);
    }

/// Gets Comment 5
    public static string GetFeedback_Write_Comment5(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Comment5");
    }

/// Sets Comment 6
    public static void SetFeedback_Write_Comment6(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Comment6", value);
    }

/// Gets Comment 6
    public static string GetFeedback_Write_Comment6(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Comment6");
    }

/// Sets Comment 7
    public static void SetFeedback_Write_Comment7(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Comment7", value);
    }

/// Gets Comment 7
    public static string GetFeedback_Write_Comment7(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Comment7");
    }

/// Sets Comment 8
    public static void SetFeedback_Write_Comment8(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Write_Comment8", value);
    }

/// Gets Comment 8
    public static string GetFeedback_Write_Comment8(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Write_Comment8");
    }

/// Sets Recipe reading complete
    public static void SetFeedback_Read_Result(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Result", value);
    }

/// Gets Recipe reading complete
    public static string GetFeedback_Read_Result(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Result");
    }

/// Sets Recipe name
    public static void SetFeedback_Read_Name(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Name", value);
    }

/// Gets Recipe name
    public static string GetFeedback_Read_Name(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Name");
    }

/// Sets Recipe number
    public static void SetFeedback_Read_Number(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Number", value);
    }

/// Gets Recipe number
    public static string GetFeedback_Read_Number(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Number");
    }

/// Sets Recipe version
    public static void SetFeedback_Read_Version(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Version", value);
    }

/// Gets Recipe version
    public static string GetFeedback_Read_Version(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Version");
    }

/// Sets Authorization level
    public static void SetFeedback_Read_Rights(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Rights", value);
    }

/// Gets Authorization level
    public static string GetFeedback_Read_Rights(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Rights");
    }

/// Sets Recipe status text
    public static void SetFeedback_Read_Status_Txt(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Status_Txt", value);
    }

/// Gets Recipe status text
    public static string GetFeedback_Read_Status_Txt(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Status_Txt");
    }

/// Sets Recipe status number
    public static void SetFeedback_Read_Status_Nr(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Status_Nr", value);
    }

/// Gets Recipe status number
    public static string GetFeedback_Read_Status_Nr(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Status_Nr");
    }

/// Sets Change user
    public static void SetFeedback_Read_Userchange(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Userchange", value);
    }

/// Gets Change user
    public static string GetFeedback_Read_Userchange(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Userchange");
    }

/// Sets Change time
    public static void SetFeedback_Read_Timechange(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Timechange", value);
    }

/// Gets Change time
    public static string GetFeedback_Read_Timechange(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Timechange");
    }

/// Sets Comment 1
    public static void SetFeedback_Read_Comment1(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Comment1", value);
    }

/// Gets Comment 1
    public static string GetFeedback_Read_Comment1(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Comment1");
    }

/// Sets Comment 2
    public static void SetFeedback_Read_Comment2(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Comment2", value);
    }

/// Gets Comment 2
    public static string GetFeedback_Read_Comment2(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Comment2");
    }

/// Sets Comment 3
    public static void SetFeedback_Read_Comment3(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Comment3", value);
    }

/// Gets Comment 3
    public static string GetFeedback_Read_Comment3(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Comment3");
    }

/// Sets Comment 4
    public static void SetFeedback_Read_Comment4(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Comment4", value);
    }

/// Gets Comment 4
    public static string GetFeedback_Read_Comment4(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Comment4");
    }

/// Sets Comment 5
    public static void SetFeedback_Read_Comment5(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Comment5", value);
    }

/// Gets Comment 5
    public static string GetFeedback_Read_Comment5(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Comment5");
    }

/// Sets Comment 6
    public static void SetFeedback_Read_Comment6(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Comment6", value);
    }

/// Gets Comment 6
    public static string GetFeedback_Read_Comment6(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Comment6");
    }

/// Sets Comment 7
    public static void SetFeedback_Read_Comment7(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Comment7", value);
    }

/// Gets Comment 7
    public static string GetFeedback_Read_Comment7(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Comment7");
    }

/// Sets Comment 8
    public static void SetFeedback_Read_Comment8(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Read_Comment8", value);
    }

/// Gets Comment 8
    public static string GetFeedback_Read_Comment8(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Read_Comment8");
    }

/// Sets Check recipe value - result
    public static void SetFeedback_Check_Result(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Result", value);
    }

/// Gets Check recipe value - result
    public static string GetFeedback_Check_Result(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Result");
    }

/// Sets Check recipe value - deviation
    public static void SetFeedback_Check_Different(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Different", value);
    }

/// Gets Check recipe value - deviation
    public static string GetFeedback_Check_Different(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Different");
    }

/// Sets Recipe name
    public static void SetFeedback_Check_Name(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Name", value);
    }

/// Gets Recipe name
    public static string GetFeedback_Check_Name(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Name");
    }

/// Sets Recipe number
    public static void SetFeedback_Check_Number(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Number", value);
    }

/// Gets Recipe number
    public static string GetFeedback_Check_Number(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Number");
    }

/// Sets Recipe version
    public static void SetFeedback_Check_Version(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Version", value);
    }

/// Gets Recipe version
    public static string GetFeedback_Check_Version(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Version");
    }

/// Sets Authorization level
    public static void SetFeedback_Check_Rights(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Rights", value);
    }

/// Gets Authorization level
    public static string GetFeedback_Check_Rights(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Rights");
    }

/// Sets Recipe status text
    public static void SetFeedback_Check_Status_Txt(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Status_Txt", value);
    }

/// Gets Recipe status text
    public static string GetFeedback_Check_Status_Txt(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Status_Txt");
    }

/// Sets Recipe status number
    public static void SetFeedback_Check_Status_Nr(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Status_Nr", value);
    }

/// Gets Recipe status number
    public static string GetFeedback_Check_Status_Nr(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Status_Nr");
    }

/// Sets Change user
    public static void SetFeedback_Check_Userchange(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Userchange", value);
    }

/// Gets Change user
    public static string GetFeedback_Check_Userchange(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Userchange");
    }

/// Sets Change time
    public static void SetFeedback_Check_Timechange(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Timechange", value);
    }

/// Gets Change time
    public static string GetFeedback_Check_Timechange(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Timechange");
    }

/// Sets Comment 1
    public static void SetFeedback_Check_Comment1(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Comment1", value);
    }

/// Gets Comment 1
    public static string GetFeedback_Check_Comment1(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Comment1");
    }

/// Sets Comment 2
    public static void SetFeedback_Check_Comment2(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Comment2", value);
    }

/// Gets Comment 2
    public static string GetFeedback_Check_Comment2(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Comment2");
    }

/// Sets Comment 3
    public static void SetFeedback_Check_Comment3(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Comment3", value);
    }

/// Gets Comment 3
    public static string GetFeedback_Check_Comment3(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Comment3");
    }

/// Sets Comment 4
    public static void SetFeedback_Check_Comment4(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Comment4", value);
    }

/// Gets Comment 4
    public static string GetFeedback_Check_Comment4(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Comment4");
    }

/// Sets Comment 5
    public static void SetFeedback_Check_Comment5(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Comment5", value);
    }

/// Gets Comment 5
    public static string GetFeedback_Check_Comment5(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Comment5");
    }

/// Sets Comment 6
    public static void SetFeedback_Check_Comment6(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Comment6", value);
    }

/// Gets Comment 6
    public static string GetFeedback_Check_Comment6(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Comment6");
    }

/// Sets Comment 7
    public static void SetFeedback_Check_Comment7(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Comment7", value);
    }

/// Gets Comment 7
    public static string GetFeedback_Check_Comment7(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Comment7");
    }

/// Sets Comment 8
    public static void SetFeedback_Check_Comment8(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_Check_Comment8", value);
    }

/// Gets Comment 8
    public static string GetFeedback_Check_Comment8(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_Check_Comment8");
    }

/// Sets Import result
    public static void SetFeedback_XMLImport_Result(this IRecipeGroup rGMRecipeGroup, string value)
    {
      rGMRecipeGroup.SetDynamicProperty("Feedback_XMLImport_Result", value);
    }

/// Gets Import result
    public static string GetFeedback_XMLImport_Result(this IRecipeGroup rGMRecipeGroup)
    {
      return (string) rGMRecipeGroup.GetDynamicProperty("Feedback_XMLImport_Result");
    }

  }
}