//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.Function;

namespace zenonExtensions
{
  public static class ScriptCollectionExtension
  {
    public static void SetScriptList(this IScriptCollection scripts, object value)
    {
      scripts.SetDynamicProperty("ScriptList", value);
    }

    public static object GetScriptList(this IScriptCollection scripts)
    {
      return (object) scripts.GetDynamicProperty("ScriptList");
    }

    public static void SetNewScript(this IScriptCollection scripts, string value)
    {
      scripts.SetDynamicProperty("NewScript", value);
    }

    public static string GetNewScript(this IScriptCollection scripts)
    {
      return (string) scripts.GetDynamicProperty("NewScript");
    }

  }
}