//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.UserAdministration;

namespace zenonExtensions
{
  public static class UserExtension
  {
/// Sets User active
    public static void SetUserActive(this IUser user, bool value)
    {
      user.SetDynamicProperty("UserActive", value);
    }

/// Gets User active
    public static bool GetUserActive(this IUser user)
    {
      return (bool) user.GetDynamicProperty("UserActive");
    }

/// Sets Full name
    public static void SetUserName(this IUser user, string value)
    {
      user.SetDynamicProperty("UserName", value);
    }

/// Gets Full name
    public static string GetUserName(this IUser user)
    {
      return (string) user.GetDynamicProperty("UserName");
    }

/// Sets Administrator
    public static void SetAdmin(this IUser user, bool value)
    {
      user.SetDynamicProperty("Admin", value);
    }

/// Gets Administrator
    public static bool GetAdmin(this IUser user)
    {
      return (bool) user.GetDynamicProperty("Admin");
    }

/// Sets User type
    public static void SetUserType(this IUser user, int value)
    {
      user.SetDynamicProperty("UserType", value);
    }

/// Gets User type
    public static int GetUserType(this IUser user)
    {
      return (int) user.GetDynamicProperty("UserType");
    }

/// Sets Power user can create/edit other power users
    public static void SetCanPowerUserModifyPowerUsers(this IUser user, bool value)
    {
      user.SetDynamicProperty("CanPowerUserModifyPowerUsers", value);
    }

/// Gets Power user can create/edit other power users
    public static bool GetCanPowerUserModifyPowerUsers(this IUser user)
    {
      return (bool) user.GetDynamicProperty("CanPowerUserModifyPowerUsers");
    }

/// Sets Locked
    public static void SetUserLocked(this IUser user, bool value)
    {
      user.SetDynamicProperty("UserLocked", value);
    }

/// Gets Locked
    public static bool GetUserLocked(this IUser user)
    {
      return (bool) user.GetDynamicProperty("UserLocked");
    }

/// Sets Lock code
    public static void SetLockCode(this IUser user, string value)
    {
      user.SetDynamicProperty("LockCode", value);
    }

/// Gets Lock code
    public static string GetLockCode(this IUser user)
    {
      return (string) user.GetDynamicProperty("LockCode");
    }

/// Sets UserLevel0
    public static void SetUserLevel0(this IUser user, uint value)
    {
      user.SetDynamicProperty("UserLevel0", value);
    }

/// Gets UserLevel0
    public static uint GetUserLevel0(this IUser user)
    {
      return (uint) user.GetDynamicProperty("UserLevel0");
    }

/// Sets UserLevel1
    public static void SetUserLevel1(this IUser user, uint value)
    {
      user.SetDynamicProperty("UserLevel1", value);
    }

/// Gets UserLevel1
    public static uint GetUserLevel1(this IUser user)
    {
      return (uint) user.GetDynamicProperty("UserLevel1");
    }

/// Sets UserLevel2
    public static void SetUserLevel2(this IUser user, uint value)
    {
      user.SetDynamicProperty("UserLevel2", value);
    }

/// Gets UserLevel2
    public static uint GetUserLevel2(this IUser user)
    {
      return (uint) user.GetDynamicProperty("UserLevel2");
    }

/// Sets UserLevel3
    public static void SetUserLevel3(this IUser user, uint value)
    {
      user.SetDynamicProperty("UserLevel3", value);
    }

/// Gets UserLevel3
    public static uint GetUserLevel3(this IUser user)
    {
      return (uint) user.GetDynamicProperty("UserLevel3");
    }

/// Sets Service Engine profile
    public static void SetLoginRTP(this IUser user, int value)
    {
      user.SetDynamicProperty("LoginRTP", value);
    }

/// Gets Service Engine profile
    public static int GetLoginRTP(this IUser user)
    {
      return (int) user.GetDynamicProperty("LoginRTP");
    }

/// Sets Equipment Groups
    public static void SetSystemModelGroup(this IUser user, object value)
    {
      user.SetDynamicProperty("SystemModelGroup", value);
    }

/// Gets Equipment Groups
    public static object GetSystemModelGroup(this IUser user)
    {
      return (object) user.GetDynamicProperty("SystemModelGroup");
    }

/// Sets Message Control user
    public static void SetIsMsgCtrlUser(this IUser user, bool value)
    {
      user.SetDynamicProperty("IsMsgCtrlUser", value);
    }

/// Gets Message Control user
    public static bool GetIsMsgCtrlUser(this IUser user)
    {
      return (bool) user.GetDynamicProperty("IsMsgCtrlUser");
    }

/// Sets PIN code
    public static void SetMsgPinCode(this IUser user, string value)
    {
      user.SetDynamicProperty("MsgPinCode", value);
    }

/// Gets PIN code
    public static string GetMsgPinCode(this IUser user)
    {
      return (string) user.GetDynamicProperty("MsgPinCode");
    }

/// Sets NA code
    public static void SetMsgNACKCode(this IUser user, string value)
    {
      user.SetDynamicProperty("MsgNACKCode", value);
    }

/// Gets NA code
    public static string GetMsgNACKCode(this IUser user)
    {
      return (string) user.GetDynamicProperty("MsgNACKCode");
    }

/// Sets Substitute person
    public static void SetMsgErsatzUser(this IUser user, string value)
    {
      user.SetDynamicProperty("MsgErsatzUser", value);
    }

/// Gets Substitute person
    public static string GetMsgErsatzUser(this IUser user)
    {
      return (string) user.GetDynamicProperty("MsgErsatzUser");
    }

/// Sets GSM
    public static void SetMsgGSM(this IUser user, string value)
    {
      user.SetDynamicProperty("MsgGSM", value);
    }

/// Gets GSM
    public static string GetMsgGSM(this IUser user)
    {
      return (string) user.GetDynamicProperty("MsgGSM");
    }

/// Sets Telephone
    public static void SetMsgPhone(this IUser user, string value)
    {
      user.SetDynamicProperty("MsgPhone", value);
    }

/// Gets Telephone
    public static string GetMsgPhone(this IUser user)
    {
      return (string) user.GetDynamicProperty("MsgPhone");
    }

/// Sets Mail
    public static void SetMsgEmail(this IUser user, string value)
    {
      user.SetDynamicProperty("MsgEmail", value);
    }

/// Gets Mail
    public static string GetMsgEmail(this IUser user)
    {
      return (string) user.GetDynamicProperty("MsgEmail");
    }

/// Sets GUID
    public static void SetGUID(this IUser user, string value)
    {
      user.SetDynamicProperty("GUID", value);
    }

/// Gets GUID
    public static string GetGUID(this IUser user)
    {
      return (string) user.GetDynamicProperty("GUID");
    }

/// Sets UserGroupsOrderImExpo
    public static void SetUserGroupsOrderImExpo(this IUser user, string value)
    {
      user.SetDynamicProperty("UserGroupsOrderImExpo", value);
    }

/// Gets UserGroupsOrderImExpo
    public static string GetUserGroupsOrderImExpo(this IUser user)
    {
      return (string) user.GetDynamicProperty("UserGroupsOrderImExpo");
    }

/// Sets Expiration time active
    public static void SetIsExpiryTimeActive(this IUser user, bool value)
    {
      user.SetDynamicProperty("IsExpiryTimeActive", value);
    }

/// Gets Expiration time active
    public static bool GetIsExpiryTimeActive(this IUser user)
    {
      return (bool) user.GetDynamicProperty("IsExpiryTimeActive");
    }

/// Sets Expiration time
    public static void SetExpiryTime(this IUser user, double value)
    {
      user.SetDynamicProperty("ExpiryTime", value);
    }

/// Gets Expiration time
    public static double GetExpiryTime(this IUser user)
    {
      return (double) user.GetDynamicProperty("ExpiryTime");
    }

  }
}