//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.UserAdministration;

namespace zenonExtensions
{
  public static class UserGroupExtension
  {
/// Sets Name
    public static void SetUserGroupName(this IUserGroup userGroup, string value)
    {
      userGroup.SetDynamicProperty("UserGroupName", value);
    }

/// Gets Name
    public static string GetUserGroupName(this IUserGroup userGroup)
    {
      return (string) userGroup.GetDynamicProperty("UserGroupName");
    }

/// Sets UserGroupLevel0
    public static void SetUserGroupLevel0(this IUserGroup userGroup, uint value)
    {
      userGroup.SetDynamicProperty("UserGroupLevel0", value);
    }

/// Gets UserGroupLevel0
    public static uint GetUserGroupLevel0(this IUserGroup userGroup)
    {
      return (uint) userGroup.GetDynamicProperty("UserGroupLevel0");
    }

/// Sets UserGroupLevel1
    public static void SetUserGroupLevel1(this IUserGroup userGroup, uint value)
    {
      userGroup.SetDynamicProperty("UserGroupLevel1", value);
    }

/// Gets UserGroupLevel1
    public static uint GetUserGroupLevel1(this IUserGroup userGroup)
    {
      return (uint) userGroup.GetDynamicProperty("UserGroupLevel1");
    }

/// Sets UserGroupLevel2
    public static void SetUserGroupLevel2(this IUserGroup userGroup, uint value)
    {
      userGroup.SetDynamicProperty("UserGroupLevel2", value);
    }

/// Gets UserGroupLevel2
    public static uint GetUserGroupLevel2(this IUserGroup userGroup)
    {
      return (uint) userGroup.GetDynamicProperty("UserGroupLevel2");
    }

/// Sets UserGroupLevel3
    public static void SetUserGroupLevel3(this IUserGroup userGroup, uint value)
    {
      userGroup.SetDynamicProperty("UserGroupLevel3", value);
    }

/// Gets UserGroupLevel3
    public static uint GetUserGroupLevel3(this IUserGroup userGroup)
    {
      return (uint) userGroup.GetDynamicProperty("UserGroupLevel3");
    }

/// Sets GUID
    public static void SetGUID(this IUserGroup userGroup, string value)
    {
      userGroup.SetDynamicProperty("GUID", value);
    }

/// Gets GUID
    public static string GetGUID(this IUserGroup userGroup)
    {
      return (string) userGroup.GetDynamicProperty("GUID");
    }

/// Sets Message Control group
    public static void SetIsMsgCtrlGroup(this IUserGroup userGroup, bool value)
    {
      userGroup.SetDynamicProperty("IsMsgCtrlGroup", value);
    }

/// Gets Message Control group
    public static bool GetIsMsgCtrlGroup(this IUserGroup userGroup)
    {
      return (bool) userGroup.GetDynamicProperty("IsMsgCtrlGroup");
    }

/// Sets Equipment Groups
    public static void SetSystemModelGroup(this IUserGroup userGroup, object value)
    {
      userGroup.SetDynamicProperty("SystemModelGroup", value);
    }

/// Gets Equipment Groups
    public static object GetSystemModelGroup(this IUserGroup userGroup)
    {
      return (object) userGroup.GetDynamicProperty("SystemModelGroup");
    }

/// Sets Automatic logout active
    public static void SetIsAutologoutActive(this IUserGroup userGroup, bool value)
    {
      userGroup.SetDynamicProperty("IsAutologoutActive", value);
    }

/// Gets Automatic logout active
    public static bool GetIsAutologoutActive(this IUserGroup userGroup)
    {
      return (bool) userGroup.GetDynamicProperty("IsAutologoutActive");
    }

/// Sets Time [min]
    public static void SetAutologoutMinutes(this IUserGroup userGroup, ushort value)
    {
      userGroup.SetDynamicProperty("AutologoutMinutes", value);
    }

/// Gets Time [min]
    public static ushort GetAutologoutMinutes(this IUserGroup userGroup)
    {
      return (ushort) userGroup.GetDynamicProperty("AutologoutMinutes");
    }

  }
}